// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDnV0R_J0aw_ZpUWIG-QNjPnPf76UcnA',
    appId: '1:30319094479:android:f20b85489b657ebebe65ba',
    messagingSenderId: '30319094479',
    projectId: 'bloom-31efb',
    storageBucket: 'bloom-31efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI6gjT2RAmVJ4c7Gp_9gqUFowhOAKrV2s',
    appId: '1:30319094479:ios:6af7003ea852b134be65ba',
    messagingSenderId: '30319094479',
    projectId: 'bloom-31efb',
    storageBucket: 'bloom-31efb.firebasestorage.app',
    androidClientId: '30319094479-5jmfhb0rf00l4b9vqreik7drhth1uc03.apps.googleusercontent.com',
    iosClientId: '30319094479-5g1robanf1krnhldm5pma5hfq0ehdc5d.apps.googleusercontent.com',
    iosBundleId: 'com.midas.evimoon',
  );
}
